#!/usr/bin/env bash
#
# Script Name: jwtdecode
#
# Author: Andreas Frank
# Date : 05/20/2019
#
# Description: The following script gets a (encoded) JWT string and decodes the information

decode_base64_url() {
  local len=$((${#1} % 4))
  local result="$1"
  if [ $len -eq 2 ]; then
    result="$1"'=='
  elif [ $len -eq 3 ]; then
    result="$1"'='
  fi
  echo "$result" | tr '_-' '/+' | base64 -D
}

# Header
decode_base64_url $(echo -n $1 | cut -d "." -f 1) | jq .

# Payload
# TIMESTAMP => decode_base64_url $(echo -n $1 | cut -d "." -f 2) | jq .
# SHOW UTC  => decode_base64_url $(echo -n $1 | cut -d "." -f 2) | jq 'if .exp then (.exp_ = (.exp|todate)) else . end'
decode_base64_url $(echo -n $1 | cut -d "." -f 2) | jq 'if .auth_time then (._auth_time_ = (.auth_time|gmtime|strftime("%Y-%m-%dT%H:%M:%S %Z"))) else . end | if .iat then (._iat_ = (.iat|gmtime|strftime("%Y-%m-%dT%H:%M:%S %Z"))) else . end | if .exp then (._exp_ = (.exp|gmtime|strftime("%Y-%m-%dT%H:%M:%S %Z"))) else . end'
